home:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: homepage
        permanent: true

homeLocale:
    path: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        _locale: '%locale%'
        route: homepage
        permanent: true
